const types = {
    SET_CONFIG: 'SET_CONFIG',
    SET_CUSTOM_STYLE: 'SET_CUSTOM_STYLE',
    SET_DARKMODE: 'SET_DARKMODE',


    SET_CARD_DATA: 'SET_CARD_DATA', //设置Card页面所需数据
    SET_LINK_DATA: 'SET_LINK_DATA', //设置Link页面所需数据
    SET_DIARY_DATA: 'SET_DIARY_DATA',   //设置Diary页面所需数据
    SET_SETTING_DATA: 'SET_SETTING_DATA',   //Setting页面所需数据


    UPDATE_CARD_CATEGORY: 'UPDATE_CARD_CATEGORY', //更新Card分类数据
    DELETE_CARD_CATEGORY: 'DELETE_CARD_CATEGORY',   //删除Card分类
    UPDATE_CARD_INFO: 'UPDATE_CARD_INFO',   //更新卡片信息
    DELETE_CARD_INFO: 'DELETE_CARD_INFO',   //删除卡片
    ADD_CARD_INFO: 'ADD_CARD_INFO',         //添加卡片

    ADD_LINK_ITEM: 'ADD_LINK_ITEM',         //添加链接
    DELETE_LINK_ITEM: 'DELETE_LINK_ITEM',   //删除链接

    ADD_DIARY_ITEM: 'ADD_DIARY_ITEM',   //添加日记
    DELETE_DIARY_ITEM: 'DELETE_DIARY_ITEM', //删除日记

    ADD_TASK_HISTORY: 'ADD_TASK_HISTORY',   //添加任务记录
    DELETE_TASK_HISTORY: 'DELETE_TASK_HISTORY', //删除任务记录
    ADD_TASK_PRESET: 'ADD_TASK_PRESET', //添加任务预设
    DELETE_TASK_PRESET: 'DELETE_TASK_PRESET',   //删除任务预设
    



}

export default types;